### PR TITLE
Fix/auctionstatechanges

### LINKED ISSUE #13: Update to handle auction changes
Before the event `AuctionEnded(uint closeTime, uint lowestBidPrice, uint totalParticipants)` was emitted right at the last bid or when someone closed the auction. This was changed because of the fact that there is a phase in between where the collected deposit has to be moved before people can start withdrawing. So now the first event is 
`AuctionDepositPending(uint closeTime, uint lowestSlotPrice, uint totalParticipants)` ( note that also the variable name changed from `lowestBidPrice` to `lowestSlotPrice` to avoid confusion with the bidValue. The later event is `AuctionEnded(uint closeTime, uint lowestSlotPrice, uint totalParticipants)`. The arguments are the same. Both events can be now used to query the endstate of the auction, so for what we have probably the first event is enough. We probably want to somehow show the state of auction also, but we will open another issue for that I guess.

### PR DESCRIPTION
**Pull request by jondoe1337**
Fixes https://github.com/trustlines-protocol/auction/issues/13

### CODE REVIEW

File: validator-auction-rest-server/lib/EthEventsClient.js [hunk 1]
```diff
@@ -106,28 +114,31 @@ export default class EthEventsClient {
...
+        const depositPending = allEvents.filter(e => e.event === 'AuctionDepositPending').length > 0
+        if (ended) {
+            return STATE_FINISHED
+        } else if (failed) {
+            return STATE_FAILED
+        } else if (started) {
+            return STATE_STARTED
+        } else if (deployed) {
+            return STATE_NOT_STARTED
+        } else if (depositPending) {
```
Comment (berndbohmeier) [inline validator-auction-rest-server/lib/EthEventsClient.js]: This is never reachable I think, because a deposit pending auction is always also started. 
I guess this has to be after failed.

**Review by berndbohmeier — CHANGES_REQUESTED** [review]
Otherwise looks good. I like that you used the constants.

File: validator-auction-rest-server/lib/EthEventsClient.js (hunk 1 above)
Comment (jondoe1337) [reply validator-auction-rest-server/lib/EthEventsClient.js]: Very good point!

**Review by berndbohmeier — APPROVED** [review]

**Comment by berndbohmeier** [comment]
LGTM
